### ISSUE TITLE
Tweet compose issue

### ISSUE THREAD

**Issue by rsahu34** [twitterdev/FabricWithTwitter#8]
Previously i installed twitter sdk through fabric. Now i upgrade it to 3.0.1, Now i am facing problem with composing tweet.
i am using this
`// Swift
let composer = TWTRComposer()

composer.setText("just setting up my Twitter Kit")
composer.setImage(UIImage(named: "twitterkit"))

// Called from a UIViewController
composer.show(from: self.navigationController!) { (result in
    if (result == .done) {
        print("Successfully composed Tweet")
    } else {
        print("Cancelled composing")
    }
}
`

and i am getting following error:

[TwitterKit] did encounter error with message "Error obtaining user auth token.": Error Domain=TWTRLogInErrorDomain Code=-1 "

Desktop applications only support the oauth_callback value 'oob' /oauth/request_token

" UserInfo={NSLocalizedDescription=

Desktop applications only support the oauth_callback value 'oob' /oauth/request_token

}
`

I have already login in my twitter app in my device. When i checking with following condition it always return to else block.
`if ([[Twitter sharedInstance].sessionStore hasLoggedInUsers]) {
   
} else {
      
}`

**Comment by andypiper** [comment]
You've already posted this on our developer forums, which is the best place for the discussion. Closing.

**Comment by rsahu34** [comment]
Thanks for your reply
I have also posted a reply against your answer please look into it as the problem is still persisting in my end.
